### ISSUE TITLE
SocketException running on AspNet Core on Linux

### ISSUE THREAD

**Issue by tessarolli** [Yortw/RSSDP#83]
This code works fine on windows, but throws this error on linux.

I'm suspecting I might be missing some .deb's on the linux box, but not sure how to find out which..

Can you help me?

Thanks

Exception:
Unhandled Exception: System.Net.Sockets.SocketException: **Protocol not available**
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.SetSocketOption(SocketOptionLevel optionLevel, SocketOptionName optionName, Int32 optionValue, Boolean silent)
   at System.Net.Sockets.Socket.SetSocketOption(SocketOptionLevel optionLevel, SocketOptionName optionName, Int32 optionValue)
   at Rssdp.SocketFactory.CreateUdpMulticastSocket(Int32 multicastTimeToLive, Int32 localPort)
   at Rssdp.Infrastructure.SsdpCommunicationsServer.BeginListeningForBroadcasts()
   at Rssdp.Infrastructure.SsdpDevicePublisherBase..ctor(ISsdpCommunicationsServer communicationsServer, String osName, String osVersion, ISsdpLogger log)
   at TessarolliSolutions.Zeus.Program.Main(String[] args) in C:\VSTS\TS\src\Zeus API\Zeus\Program.cs:line 69

Code:
_Publisher = new SsdpDevicePublisher(new SsdpCommunicationsServer(new SocketFactory(HardwareInfo.GetIPAddress().ToString())));
_Publisher.StandardsMode = SsdpStandardsMode.Relaxed;
_Publisher.AddDevice(PublishDevice());

**Comment by Yortw** [comment]
Hi,

The only protocol I'm aware this needs is UDP. I'm afraid I'm not familiar with Linux, 'debs' or mono, and have no device(s) on which to test this so I'm not much help.

If there is a 'deb' to add UDP support then I guess try installing that, otherwise perhaps try Googling for that error details and mono and .net.

**Comment by Yortw** [comment]
Sorry, that is not totally accurate... UDP is used primarily, but also HTTP which also requires TCP. In the error above it looks like (multicast) UDP is what is trying to be accessed though.

**Comment by Yortw** [comment]
Apologies for leaving this issue unattended for so long. Its likely you've moved on. However, in case you haven't given up, or for anyone else who stumbles across this issue;

The new V5 release has different targets and potentially different dependencies. I don't have a debian device to test on, nor the time/knowledge to setup a virtual box for testing. If someone could test the latest version in a relevant environment and see if anything has changed, that would be great.

I did a little bit of research and it does seem like UDP is an 'optional' component of some linux systems, so it might be that's what needs to be installed/enabled, but I'm not sure of the exact steps for any given distro.
